# Generated by Django 3.2.8 on 2021-10-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bio', models.TextField(blank=True, default='I am the BOSS')),
            ],
        ),
    ]
