# Generated by Django 3.2.8 on 2021-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='something@bracu.com', max_length=254),
            preserve_default=False,
        ),
    ]
